---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: dragonfly
spec:
  interval: 5m
  chart:
    spec:
      chart: dragonfly-stack
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: dragonfly
  values:
    replicas: 2
    redis:
      enabled: true
