apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app: dragonfly
  name: dragonfly
spec:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 200m
      memory: 750Mi
