apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-prod
  namespace: flux-system
spec:
  interval: 10m
  path: ./course-app/overlays/production
  prune: true
  targetNamespace: production
  sourceRef:
    kind: GitRepository
    name: flux-system
