apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-dev
  namespace: flux-system
spec:
  interval: 10m
  path: ./course-app/overlays/development
  prune: true
  targetNamespace: development
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
