apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: dragonfly-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ../../infrastructure/controllers/dragonfly
